dist: trusty
sudo: false
language: python
python:
    - "2.7"
    # - "3.5"
    # - "3.6"
    # - "nightly"
before_install:
    - pip install --upgrade setuptools pip
    - pip install --upgrade virtualenv
install:
    - pip install --upgrade flake8 pylint
    - pip --version
    - virtualenv --version
    - flake8 --version
    - pylint --version
    - git --version
# before_script:
script:
    - flake8 --count ${TRAVIS_BUILD_DIR}
    # Do not run pylint on nightly Python versions as they may not be compatible
    # - |
    #     if [[ $TRAVIS_PYTHON_VERSION != "nightly" ]]; then
    #         pylint ${TRAVIS_BUILD_DIR}
    #     fi
